### ISSUE TITLE
There seems to be some issue with chainlit/message.py

### ISSUE THREAD

**Issue by nitish2507** [onepointconsulting/hr_job_cv_matcher#3]
2024-01-18 16:06:42 - Template count: 2
2024-01-18 16:06:42 - 'str' object has no attribute 'to_dict'
Traceback (most recent call last):
  File "/Users/nitish/Library/Caches/pypoetry/virtualenvs/hr-job-cv-matcher-JiiZFaw_-py3.11/lib/python3.11/site-packages/chainlit/utils.py", line 40, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nitish/Downloads/developments/hr_job_cv_matcher/./hr_job_cv_matcher/ui/matcher_chainlit.py", line 64, in init
    await start_process_applications_and_cvs(application_docs, cv_docs)
  File "/Users/nitish/Downloads/developments/hr_job_cv_matcher/./hr_job_cv_matcher/ui/matcher_chainlit.py", line 451, in start_process_applications_and_cvs
    await process_with_settings(settings)
  File "/Users/nitish/Downloads/developments/hr_job_cv_matcher/./hr_job_cv_matcher/ui/matcher_chainlit.py", line 89, in process_with_settings
    ] = await process_applications_and_cvs(application_docs, cvs_docs, score_weights)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nitish/Downloads/developments/hr_job_cv_matcher/./hr_job_cv_matcher/ui/matcher_chainlit.py", line 140, in process_applications_and_cvs
    ] = await process_job_description_and_candidates(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nitish/Downloads/developments/hr_job_cv_matcher/./hr_job_cv_matcher/ui/matcher_chainlit.py", line 192, in process_job_description_and_candidates
    _, skill_results = await process_skills_llm_chain(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nitish/Downloads/developments/hr_job_cv_matcher/./hr_job_cv_matcher/ui/matcher_chainlit.py", line 305, in process_skills_llm_chain
    return await process_generic_extraction(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nitish/Downloads/developments/hr_job_cv_matcher/./hr_job_cv_matcher/ui/matcher_chainlit.py", line 288, in process_generic_extraction
    await results_msg.stream_token(
  File "/Users/nitish/Library/Caches/pypoetry/virtualenvs/hr-job-cv-matcher-JiiZFaw_-py3.11/lib/python3.11/site-packages/chainlit/message.py", line 109, in stream_token
    msg_dict = self.to_dict()
               ^^^^^^^^^^^^^^
  File "/Users/nitish/Library/Caches/pypoetry/virtualenvs/hr-job-cv-matcher-JiiZFaw_-py3.11/lib/python3.11/site-packages/chainlit/message.py", line 202, in to_dict
    _dict["prompt"] = self.prompt.to_dict()
                      ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_dict'

**Comment by kneuskens** [comment]
I also have this issue. is there a solution for that?
