### ISSUE TITLE
page_content none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by stevenbaert** [onepointconsulting/hr_job_cv_matcher#4]
Hi,

Love this project! Wanted to give it a go (install worked fine) but when uploading a document I get the error below.
Could you help me with this?

Thanks!
S

---

Chatbot

14:38:28

May the work-force be with you.

14:38:28

Please upload job description files!

14:38:34

Processing testcv.pdf Please wait ...

Error

14:38:34

1 validation error for Document
page_content
none is not an allowed value (type=type_error.none.not_allowed)

**Comment by stevenbaert** [comment]
Update: one step further :-), the tmp-folder was missing in the pdf_to_image_server

Though now another error: "Traceback (most recent call last):"

Agile environments.
=== CV END: ===

The matching skills are: RESTful APIs, SQL, JSON, XML
The missing skills are: Cloud-based Application Support, integration platforms, Business Intelligence BI, Analytical reporting using PowerBI, Exposure to ITIL, Knowledge in Al, Azure Logic apps, Azure Data Factory

====== Example end: =====

2024-02-21 14:56:28 - Template count: 2
2024-02-21 14:56:28 - 'str' object has no attribute 'to_dict'
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/DEV-CVMatcher/lib/python3.11/site-packages/chainlit/utils.py", line 40, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steven/Scripts/Python/01.DEV/CV-Matcher/hr_job_cv_matcher/./hr_job_cv_matcher/ui/matcher_chainlit.py", line 64, in init
